version: '3'
services:
    server:
        build: 
            context: ./server
            target: dev
        ports:
            - '5000:5000'
        depends_on:
            - db
        environment:
            - DATABASE_URL=postgres://postgres:password@db:5432/postgres

    client:
        build: 
            context: ./client
            target: dev
        ports:
            - '5173:5173'
        environment:
            - NODE_ENV=development

    db:
        image: postgres:latest
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data/
            - ./scripts/db:/docker-entrypoint-initdb.d
volumes:
    postgres_data:

networks:
    default:
        name: 'my_todo_list_network'
